name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install Yarn
      run: npm install -g yarn
    
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    
    - run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
    
    # Add your build, test, or deploy steps here
