name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    # Install Yarn
    - name: Install Yarn
      run: npm install -g yarn

    # Install dependencies using Yarn
    - name: Install Dependencies
      run: yarn install

    # Build your project (if you have a build step)
    - name: Build
      run: yarn build
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
